### PR TITLE
Make print_profile_docs work in dbt cloud

### PR DESCRIPTION
**Pull request by ngocanhtt0805**
## Description & motivation
Hi @stumelius,

In our current project, we have implemented your dbt-profiler package and it’s wonderful to give our developer and QA ability to quickly view the relation profile.
But we’re using dbt Cloud and developing our dbt project here and it’s the pity that `print_profile_docs`  doesn’t work in Cloud due to `print_table` method.
That why I came up with the macro `print_profile_docs_dbtc` which makes use of `dbt_profiler.get_profile_table` to make it compatible to dbt Cloud. And I would like to contribute that as a workaround for people who are developing in dbt Cloud.

## Checklist
- [x] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered):
    - [ ] Postgres
    - [ ] BigQuery
    - [x] Snowflake
    - [ ] Redshift
    - [ ] SQL Server
    - [ ] Databricks
- [ ] I have written tests for new macros (either as dbt schema tests in `integration_tests/models`, dbt data tests in `integration_tests/tests` or integration tests in the [CI workflow](workflows/main.yml))
- [ ] I have updated the README.md (if applicable)

### CODE REVIEW

**Comment by stumelius** [comment]
@ngocanhtt0805 Wow, this is awesome! 💯 One suggestion: If there's a way to check if the macro is being called in dbt Cloud then I'd propose doing something like this in the existing `print_profile_docs` macro:

```
{% macro print_profile_docs(relation=none, relation_name=none, docs_name=none, schema=none, database=none, exclude_measures=[], include_columns=[], exclude_columns=[], max_rows=none, max_columns=13, max_column_width=30, max_precision=none, where_clause=none) %}

{%- set results = dbt_profiler.get_profile_table(relation=relation, relation_name=relation_name, schema=schema, database=database, exclude_measures=exclude_measures, include_columns=include_columns, exclude_columns=exclude_columns, where_clause=where_clause) -%}

{% if docs_name is none %}
  {% set docs_name = 'dbt_profiler__' + relation_name %}
{% endif %}

{% if execute %}
  {{ print('{% docs ' + docs_name + '  %}') }}
  -- How to check if macro is called in dbt Cloud?
  {% set is_dbt_cloud = ... %}
  {% if not is_dbt_cloud %}
    {% do results.print_table(max_rows=max_rows, max_columns=max_columns, max_column_width=max_column_width, max_precision=max_precision) %}
  {% else %}
    -- This is a workaround for dbt Cloud, which does not support the print_table method
    {% do dbt_profiler.print_table(table=results, max_rows=max_rows, max_columns=max_columns, max_column_width=max_column_width, max_precision=max_precision, show=False) %}
  {% endif %}
  {{ print('{% enddocs %}') }}
{% endif %}

{% endmacro %}
```

Here the custom printing logic is implemented in a `print_table` macro. What do you think? (edited)

**Comment by ngocanhtt0805** [comment]
Hi @stumelius 
Sorry for late response.
Thank you so much for your feedback. I've modified the macro `print_profile_docs` followed by your suggestion. Can you kindly help have a look, many thanks

**Comment by stumelius** [comment]
This is perfect, thanks! ❤️ I'm merging this now

**Comment by stumelius** [comment]
This is now included in the latest 0.8.0 release https://github.com/data-mie/dbt-profiler/releases/tag/0.8.0

**Pull request merged**
